id: I91192FFE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:02:06+00:00'
last_modified: '2022-06-08T17:20:11.410936+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15817
  title: གསུང་འབུམ། བློ་བཟང་འཇམ་དབྱངས་སྨོན་ལམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    61B4:
      image_group_id: I1KG15819
      title: ''
      total_pages: 444
      order: 1
      base_file: 61B4.txt
    88D2:
      image_group_id: I1KG15820
      title: ''
      total_pages: 494
      order: 2
      base_file: 88D2.txt
    769E:
      image_group_id: I1KG15821
      title: ''
      total_pages: 412
      order: 3
      base_file: 769E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
