id: I91192FFE
legacy_id: P010761
ocr_import_info:
  bdrc_scan_id: W1KG15817
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T16:58:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T05:27:14.831713+00:00'
last_modified: 2022-08-27 13:29:11.512918
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG15817
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG15817
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་འཇམ་དབྱངས་སྨོན་ལམ།
  author: ཀེའུ་ཚང་འཇམ་དབྱངས་སྨོན་ལམ།
statistics:
  ocr_word_mean_confidence_index: 0.9161610183590085
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG15820:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15820
      total_pages: 494
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG15820.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9167811951047192
    legacy_id: v002
  I1KG15819:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15819
      total_pages: 444
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15819.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9291928444143666
    legacy_id: v001
  I1KG15821:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15821
      total_pages: 412
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG15821.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9025340901767152
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
